name: Helix PR CI
on:
  pull_request:
    branches: [ master, metaclient ] # TODO: remove side branch
    paths-ignore:
      - '.github/**'
      - 'helix-front/**'
      - '**/*.md'

jobs:
  PR_CI:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Delete frontend-maven-plugin dir
      run: rm -rf .m2\repository\com\github\eirslett
    - name: Build with Maven
      run: mvn clean install -Dmaven.test.skip.exec=true -DretryFailedDeploymentCount=5
    - name: Run All Tests
      run: mvn -q -fae -Dsurefire.rerunFailingTestsCount=5 test
    - name: Print Tests Results
      run: .github/scripts/printTestResult.sh
      if: ${{ success() || failure() }}
